title: IVYAR Governance Portal
description: Official documentation, architecture, and legal framework of IVYAR Platform.
remote_theme: just-the-docs/just-the-docs
logo: /assets/logo/ivyar-logo.svg
color_scheme: light
url: https://yarmis.github.io
baseurl: /ivyar-governance
